name: C/C++ CI

on:
  push:
    branches:
      - master
      - MPI_Development
      - cmake_development
      - parUpscale

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    # Get dependencies
    - name: Get dependencies
      run: sudo apt-get install -y openmpi-bin openmpi-common libopenmpi-dev cppcheck doxygen
          
    # Checkout v2 : https://github.com/actions/checkout
    - uses: actions/checkout@v2
      
    # Make the project
    - name: cmake
      run: cmake . && make
  
    # Run cmake tests
    - name: ctest
      run: make test
    
    # Run cppcheck
    - name: cppcheck
      run: cppcheck --enable=all --force .

    # Generate and publish doxygen documentation to wiki
    #- name: Upload Wiki documentation
    #  uses: SwiftDocOrg/github-wiki-publish-action@v1
    #  with:
    #    path: "docs/html"
    #  env:
    #    GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        
    - name: Publish generated content to GitHub Pages
      uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
      with:
        dir: docs/html
        branch: master
        token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
