name: C/C++ CI

on:
  push:
    branches:
      - master
      - MPI_Development
      - cmake_development
      - parallelPersistence

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    # Get dependencies
    - name: Get dependencies
      run: sudo apt-get install -y openmpi-bin openmpi-common libopenmpi-dev cppcheck
          
    # Checkout v2 : https://github.com/actions/checkout
    - uses: actions/checkout@v2
      
    # Make the project
    - name: cmake
      run: cmake . && make
  
    # Run cmake tests
    - name: ctest
      run: make test
    
    - name: cppcheck
      run: cppcheck --enable=all --force .
